# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - tasksheetapi(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: tasksheetapi    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './package'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: create package folder
      run: |
        mkdir package
        cp "package.json" "package/package.json"
        cp "swagger.yaml" "package/swagger.yaml"
        cp -R "dist" "package/dist"

    - name: Install Prod packages
      run: |         
        npm install --production
        npm install --save tslib
      working-directory: ./package

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE226D11330D4CB1A6FC08B6F7CBE55C }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

